CREATE TABLE wintermorevault_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password TEXT NOT NULL,
  nickname TEXT,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  date_modified TIMESTAMP
);

ALTER TABLE wintermorevault_events
  ADD COLUMN
    author_id INTEGER REFERENCES wintermorevault_users(id)
    ON DELETE SET NULL;
