CREATE TABLE wintermorevault_comments (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    event_id INTEGER
        REFERENCES wintermorevault_events(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES wintermorevault_users(id) ON DELETE CASCADE NOT NULL
);
